## What I am exercising:

* Crating Rank 1 and Rank 2 **ndarrays**
* Accessing elements in ndarrays using basic indexing
* Using built-in functions to quickly and easily create useful ndarrays

In [2]:
import numpy as np

an_array = np.array([3,33,333]) #Rank 1 array

print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [5]:
#ndarrays are mutamble 
#ndarrays accept only int

an_array[0] = 888

print(an_array)

[888  33 333]


## Matrix

In [6]:
another = np.array([[11,12,13],[21,22,23]]) #Rank 2 array
print(another)
print("The shape is 2 rows, 3 columns: ", another.shape) #rows x columns
print("Accesing elements [0,0], [0,1] and [1,0] of the ndarray: ", another[0,0], another[0,1], another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accesing elements [0,0], [0,1] and [1,0] of the ndarray:  11 12 21


In [7]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [8]:
ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [9]:
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [10]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


Array of ones

In [13]:
print(ex4.shape)
print(ex4[0,1])

(1, 2)
1.0


In [14]:
#random
ex5 = np.random.random((2,2))
print(ex5)

[[0.72178043 0.74321865]
 [0.86921846 0.49485997]]


## Exercising:

* Using slice indexing to access subsets of an ndarray
* Recognizing that such indexing creates a second reference to the same underlying data

In [15]:
array3 = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(array3)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [17]:
#slicing

a3_slice = array3[:2, 1:3] #[columns 0,1, rows 1,2]
print(a3_slice)

[[12 13]
 [22 23]]


In [18]:
print(a3_slice[0,0])

12


In [21]:
print("Before: ", array3[0,1])
a3_slice[0,0] = 1000
print("After: ", array3[0,1])

Before:  12
After:  1000


In [28]:
a3_slice = np.array(array3[:2, 1:3]) #copy of array3
print("Before: ", array3[0,1])

a3_slice[0,0] = 12
print("After: ", array3[0,1])


Before:  1000
After:  1000


The a3_slice is a copy of array3 and now it doesn't change array3.

In [30]:
array3[0,1] = 12
print(array3)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [31]:
row_rank1 = array3[1,:] #Rank 1 view

print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [32]:
row_rank2 = array3[1:2, :]

print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [33]:
col_rank1 = array3[:, 1]
col_rank2 = array3[:, 1:2]

print(col_rank1, col_rank1.shape) #Rank 1
print()
print(col_rank2, col_rank2.shape) #Rank 2

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [35]:
# Create an array of indices
col_indices = np.array([0,1,2,0])
print('Col indices picked: ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked: ', row_indices)

Col indices picked:  [0 1 2 0]

Rows indices picked:  [0 1 2 3]


In [36]:
for row, col in zip(row_indices, col_indices):
    print(row, ", ", col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [41]:
array4 = np.random.random((4,3))
print(array4)
print('Values in the array at those indices: ', array4[row_indices, col_indices])

[[0.44147051 0.79830251 0.42191227]
 [0.83599946 0.68889922 0.52234495]
 [0.27535596 0.82095824 0.08762017]
 [0.72012905 0.57642261 0.99010367]]
Values in the array at those indices:  [0.44147051 0.68889922 0.08762017 0.72012905]


In [42]:
#Change one element from each row using the indices selected
array4[row_indices, col_indices] +=200

print('\nChanged Array:')
print(array4)


Changed Array:
[[200.44147051   0.79830251   0.42191227]
 [  0.83599946 200.68889922   0.52234495]
 [  0.27535596   0.82095824 200.08762017]
 [200.72012905   0.57642261   0.99010367]]


In [43]:
arr = np.random.random((3,3))
print(arr)

[[0.98286487 0.78795702 0.66995962]
 [0.64233478 0.1816662  0.70222984]
 [0.0974553  0.04286362 0.44388343]]


In [44]:
print(arr[:2])

[[0.98286487 0.78795702 0.66995962]
 [0.64233478 0.1816662  0.70222984]]
